name: cd-pipeline
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  cd_pipeline:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - name: Deploy Appication
        working-directory: /root/bookmark-management/deployment
        run: |
          echo "Deploying application..."
          git pull
          docker rm -f bookmark_service
          docker-compose pull bookmark_service
          docker-compose up -d bookmark_service
          docker system prune -f